EPITECH-Strasbourg-2021/CPP-Arcade-Spec

IGameModule.hpp
IGraphicLib.hpp

Add a function to get the name of the library or the game

[+] getName

---

README.md
entryPoint.cpp

Add an instruction for standardize the name of the entryPoint

[+] entryPoint (Fix #6)

---

TextBox.hpp

minor typo error

---

PixelBox.hpp

This PR is part of an initiative to refactor how rendering is handled originating from Corentin Leroy.
This allows non-uniformly colored PixelBoxes to be represented and passed around between libraries.

Allow for non-uniform PixelBoxes + Refactoring

---

IGameLib.hpp
IGraphicLib.hpp

This PR addresses issue #24 and removes constructors that shouldn't be there.

Removed constructors in interfaces + Stricter constness

---

TextBox.hpp

Added default destructor to TextBox

---

IGameLib.hpp

Because of this
```c++
IGameLib game = new IGameLib();
game.initGame();
game.stopGame();
[...]
```

[~] Change name of function in IGameLib

---

PixelBox.hpp

This is a leftover from PR #19 and isn't used anymore.

Removing unused include

---

PixelBox.hpp
TextBox.hpp

Added some methods on TextBox.
Nothing fundamentally different but makes more use of the templated `Vect<size_t>` type.

QoL changes on TextBox

---

PixelBox.hpp

Added const to PixelBox::getPixel() method.

---

IGraphicLib.hpp

This PR results from the earlier-than-expected merge of PR #44.
It includes the documentation that was originally requested.

Added Event Handling documentation for IGraphicLib

---

Vect.hpp

[-] Remove shady std::hash

---

IGraphicLib.hpp

Add the possibility to set the title of the window (for SFML, libcaca, etc)

[+] possibility to set the title

---

IGraphicLib.hpp

Cancel PR #51, default arguments on virtual or override methods are prohibited.

Cancel PR #51, implementation prohibited

---

IGameLib.hpp

#57 isn't getting any further, it seems.
So I'm making this proposal to try enabling everyone to start implementing things.
This also tries to lighten the former `IGameLib::loop()` function who was going to be gigantic with a lot of unrelated things to cover + fixes the fact that if the Core changes the keys it treats for itself, the games don't need to be rewritten.

Separating game logic from event handling + Fix #57

---

IGameLib.hpp

Permit to make this :
```C++
const std::string &Arcade::SolarFox::getName() const
{
return "Solar Fox";
}
```

[-] Return reference in getName

---

IGraphicLib.hpp

Added the possibility to set the title of the window

[+] Setting title for the window

---

IGameLib.hpp

Allow the game to setup is own score system

Add Player name setter

---

IGameLib.hpp

To call at the end of the execution of the game (after the player loose or win) for getting his score

[+] getScore

---

IGameLib.hpp

Return a bool for `applyEvent` and `update` to tell to the core that the player has win or loose

[~] return bool

---

IGameLib.hpp

[-] remove useless func
